name: bluetooth_app
description: "블루투스기반 스마트 의약품 관리"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  drift: ^2.25.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqlite3_flutter_libs: ^0.5.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.25.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_icon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/images/splash_icon.png # 앱 실행 시 표시할 이미지 
  android: true
  ios: false
  fullscreen: true
        
       